finalProject/urls.py
from django.conf.urls import  url
from car_prediction.api import CarAdList ,CarAdDetail
from rest_framework.urlpatterns import format_suffix_patterns




from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from user.views import register, profile,profile_update ,load_regions
from django.contrib.auth import views
from home.views import home
from search.views import used_search, new_search
from car_prediction.views import prediction ,userSubmit,chrome ,home2
from car.views import add_used_car ,used_car,new_car ,load_models ,add_new_car ,update_new_car \
      ,update_used_car ,delete_new_car,delete_used_car

urlpatterns = [
      path('admin/', admin.site.urls),
      # home app____________________________________________________________________________
      path('', home, name='home'),
      # user app______________________________________________________________________
      path('register/', register.as_view(), name='register'),
      path('login/', views.LoginView.as_view(template_name='user/login.html'), name='login'),
      path('logout/', views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
      path('profile/<int:pk>/',profile, name='profile'),
      path('profile/update/',profile_update, name='profile_update'),

      # search app____________________________________________________________
      path('used_search/<str:comp>/<str:model>/', used_search.as_view(), name='used_search'),
      path('new_search/<str:comp>/<str:model>/', new_search.as_view(), name='new_search'),
      # car app_______________________________________________________
      path('used_car/<int:pk>/', used_car.as_view(), name='used_car'),
      path('new_car/<int:pk>/',new_car.as_view(), name='new_car'),

      path('add_used_car/', add_used_car, name='add_used_car'),
      path('add_new_car/', add_new_car, name='add_new_car'),

      path('update_new_car/<int:pk>/', update_new_car, name='update_new_car'),
      path('update_used_car/<int:pk>/', update_used_car, name='update_used_car'),

      path('delete_new_car/<int:pk>/', delete_new_car.as_view(), name='delete_new_car'),
      path('delete_used_car/<int:pk>/', delete_used_car.as_view(), name='delete_used_car'),
      # ajax__________________________________________________________
      path('ajax/load_models/' ,load_models ,name ='ajax_load_models' ),
      path('ajax/load_regions/' ,load_regions ,name ='ajax_load_regions' ),

      # prediction__________________________________________________________________
      path('prediction/', prediction, name='prediction'),
                    url(r'^x$', home2, name='home2'),

                    url(r'^userSubmit',userSubmit, name="userSubmit"),

                    url(r'^chrome',chrome, name="chrome"),

                    url(r'^api/ads/$',CarAdList.as_view()),
                    url(r'^api/ads/(?P<idFromSite>[0-9]+)/$', CarAdDetail.as_view())

  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = format_suffix_patterns(urlpatterns)

car/models.py
from django.db import models
from django.contrib.auth.models import User

class company(models.Model):
    الماركة = models.CharField(max_length=20)

    def __str__(self):
        return self.الماركة

class model(models.Model):
    companyId =models.ForeignKey(company ,on_delete=models.CASCADE)
    الموديل = models.CharField(max_length=20)

    def __str__(self):
        return self.الموديل

class newCar(models.Model):
    modelId = models.ForeignKey(model ,on_delete=models.CASCADE)
    الفئة =models.CharField(max_length=20)
    السنة = models.IntegerField()
    السعر = models.FloatField(max_length=10)

class image(models.Model):
    carID =models.ForeignKey(newCar ,on_delete=models.CASCADE)
    صورة = models.ImageField(default='default.jpg', upload_to='car_img')

class carDetails_Text(models.Model):
    name =models.CharField(max_length=20 , primary_key=True)

class carDetails_Bool(models.Model):
    name =models.CharField(max_length=20 , primary_key=True)


class carContents_Text(models.Model):
    class Meta:
        unique_together =(('carId', 'carDetailsId'),)

    carId =models.ForeignKey(newCar,on_delete=models.CASCADE )
    carDetailsId =models.ForeignKey(carDetails_Text,on_delete=models.CASCADE )
    value =models.CharField(max_length=50)

class carContents_Bool(models.Model):
    class Meta:
        unique_together =(('carId', 'carDetailsId'),)

    carId =models.ForeignKey(newCar,on_delete=models.CASCADE )
    carDetailsId =models.ForeignKey(carDetails_Bool,on_delete=models.CASCADE )
    value =models.BooleanField()

class publishedCar(models.Model):
    customerId =models.ForeignKey(User,on_delete=models.CASCADE )
    modelId = models.ForeignKey(model, on_delete=models.CASCADE)
    الفئة = models.CharField(max_length=20)
    السنة = models.IntegerField()
    السعر = models.FloatField(max_length=10)


class used_image(models.Model):
    carId =models.ForeignKey(publishedCar ,on_delete=models.CASCADE)
    صورة = models.ImageField(default='default.jpg', upload_to='car_img')

class publishedCarDetails_Text(models.Model):
    name =models.CharField(max_length=20 ,primary_key=True)

class publishedCarDetails_Bool(models.Model):
    name =models.CharField(max_length=20 ,primary_key=True)

class publishedCarContents_Text(models.Model):
    class Meta:
        unique_together =(('publishedCarId', 'publishedCarDetailsId'),)

    publishedCarId =models.ForeignKey(publishedCar,on_delete=models.CASCADE )
    publishedCarDetailsId =models.ForeignKey(publishedCarDetails_Text,on_delete=models.CASCADE )
    value =models.CharField(max_length=50)

class publishedCarContents_Bool(models.Model):
    class Meta:
        unique_together =(('publishedCarId', 'publishedCarDetailsId'),)

    publishedCarId =models.ForeignKey(publishedCar,on_delete=models.CASCADE )
    publishedCarDetailsId =models.ForeignKey(publishedCarDetails_Bool,on_delete=models.CASCADE )
    value =models.BooleanField()

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render,redirect
from car.models import newCar ,company
from .form import search_form

def home(request):
    companies =company.objects.all()
    cars = newCar.objects.all()
    form = search_form(request.POST or None)

    context ={
        'companies' :companies ,
        'cars' :cars ,
        'form' :form
    }

    if request.method == 'POST':
        if form.is_valid():
            comp =form.cleaned_data['الماركة']
            model =form.cleaned_data['الموديل']
            type =form.cleaned_data['نوع_السيارة']


            if type == '1':
                return redirect('new_search', comp=comp ,model =model)

            elif type == '2':
                return redirect('used_search', comp=comp, model=model)




    return render(request ,'home/home.html' ,context)

home/templates/home/home.html
{% extends 'user/base.html' %}
{% load static %}

{% block css_file %}"{% static 'home/css/home.css' %}"{% endblock %}


{% block content %}
<div class="home">

    <!-- loading---------------------------->
    <div class="loadingpage">
        <div class="counter2">
            <h1>0</h1>
        </div>
    </div>


    <!-- ------------------------
                    header
            ------------------------------- -->
    <header>
        <div class="overlay block" id="home"></div>
        <div class="container">


            <div class="row">
                <div class="caption">
                    <h1>Company Name</h1>
                    <p>الاختيار الانسب لسيارتك</p>
                    {%if user.is_superuser%}
                    <a class="btn admin_Button" href="{%url 'add_new_car' %}">اضافة سيارة جديدة</a>
                    <a class="btn admin_Button" href="admin/">صفحة الادمن</a>
                    {%endif%}
                    <a class="scroll" href="{%url 'home2'%}" data-scroll="about" style="display:block"><button class="btn rounded-0 btn-danger" style="width: 400px;">تنبأ بسعر سيارتك </button></a>

                </div>
            </div>
        </div>
    </header>
<!-------------------------
     search
    ----------------------------->
    <div class="search">
        <form method="POST" id="search_form" data-models-url="{% url 'ajax_load_models' %}" novalidate> {% csrf_token %}
        <div class="row">
            {% for field in form %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="row mb-3">
                    <span class="dark col-4">{{field.label_tag }} </span>
                    <span class=" data col">{{field}}</span>
                </div>
                {% for error in field.errors %}
                    <div class="col red ">{{ error }}</div>
                    {%endfor%}
            </div>
            {%endfor%}
        </div>
        <input class='send btn' type="submit" value="بحث">
    </form>
    </div>


    <!-------------------------
      Gallery
    ----------------------------->
    <div class="scroll">
        <div class="wrap">
            <div class="portfolio block" id="portfolio">
                <div class="container">
            <!---first row have header of section-->
                    <div class="row pt-5 pb-3">
                        <div class="col">
                            <h2 class="section-title text-uppercase" style="float: right; color: #d72c1a; font-size: 50px;">معرض السيارات الجديدة </h2>

                        </div>
                    </div>
                    <div class="row wid">
                        <div class="col">
                            <ul class="list-group">
                                <li class="list-group-item active2"data-class="all" >الكل</li>
                                {%for comp in companies %}
                                <li class="list-group-item "data-class=".{{comp.الماركة}}" >{{comp.الماركة}}</li>
                                {%endfor%}
                            </ul>
                        </div>
                    </div>

                    <div class="row mt-5">
                        {%for car in cars %}
                        <div class=" img_c_d text-center col-sm-12 col-md-6 col-lg-4 mb-5 box {{car.modelId.companyId.الماركة}}">
                            <img class ='img_c_i' style="height:70%" src="{{ car.image_set.first.صورة.url}}" alt="" title="" />
                            <h4 class="text-center text-uppercase">{{ car.modelId.الموديل }} </h4>
                            <h5 class="text-center text-uppercase">{{ car.الفئة }} </h5>
                            <button class="btn send"><a href="{%url 'new_car' car.id%}">عرض التفاصيل</a></button>
                        </div>
                        {%endfor%}
                     </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_file %}"{% static 'home/js/home.js' %}"{% endblock %}

{% block js_content %}
$("#id_الماركة").change(function () {
      var url = $("#search_form").attr("data-models-url");  // get the url of the load_models view
      var compId = $(this).val();  // get the selected company ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request 😊 localhost:8000/hr/ajax/load-cities/)
        data: {
          'الماركة': compId
          // add the country id to the GET parameters
        },
        success: function (data) {   // data is the return of the load_models view function
          $("#id_الموديل").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
{% endblock %}