finalProject/urls.py
from django.conf.urls import  url
from car_prediction.api import CarAdList ,CarAdDetail
from rest_framework.urlpatterns import format_suffix_patterns




from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from user.views import register, profile,profile_update ,load_regions
from django.contrib.auth import views
from home.views import home
from search.views import used_search, new_search
from car_prediction.views import prediction ,userSubmit,chrome ,home2
from car.views import add_used_car ,used_car,new_car ,load_models ,add_new_car ,update_new_car \
      ,update_used_car ,delete_new_car,delete_used_car

urlpatterns = [
      path('admin/', admin.site.urls),
      # home app____________________________________________________________________________
      path('', home, name='home'),
      # user app______________________________________________________________________
      path('register/', register.as_view(), name='register'),
      path('login/', views.LoginView.as_view(template_name='user/login.html'), name='login'),
      path('logout/', views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
      path('profile/<int:pk>/',profile, name='profile'),
      path('profile/update/',profile_update, name='profile_update'),

      # search app____________________________________________________________
      path('used_search/<str:comp>/<str:model>/', used_search.as_view(), name='used_search'),
      path('new_search/<str:comp>/<str:model>/', new_search.as_view(), name='new_search'),
      # car app_______________________________________________________
      path('used_car/<int:pk>/', used_car.as_view(), name='used_car'),
      path('new_car/<int:pk>/',new_car.as_view(), name='new_car'),

      path('add_used_car/', add_used_car, name='add_used_car'),
      path('add_new_car/', add_new_car, name='add_new_car'),

      path('update_new_car/<int:pk>/', update_new_car, name='update_new_car'),
      path('update_used_car/<int:pk>/', update_used_car, name='update_used_car'),

      path('delete_new_car/<int:pk>/', delete_new_car.as_view(), name='delete_new_car'),
      path('delete_used_car/<int:pk>/', delete_used_car.as_view(), name='delete_used_car'),
      # ajax__________________________________________________________
      path('ajax/load_models/' ,load_models ,name ='ajax_load_models' ),
      path('ajax/load_regions/' ,load_regions ,name ='ajax_load_regions' ),

      # prediction__________________________________________________________________
      path('prediction/', prediction, name='prediction'),
                    url(r'^x$', home2, name='home2'),

                    url(r'^userSubmit',userSubmit, name="userSubmit"),

                    url(r'^chrome',chrome, name="chrome"),

                    url(r'^api/ads/$',CarAdList.as_view()),
                    url(r'^api/ads/(?P<idFromSite>[0-9]+)/$', CarAdDetail.as_view())

  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = format_suffix_patterns(urlpatterns)

car/models.py
from django.db import models
from django.contrib.auth.models import User

class company(models.Model):
    الماركة = models.CharField(max_length=20)

    def __str__(self):
        return self.الماركة

class model(models.Model):
    companyId =models.ForeignKey(company ,on_delete=models.CASCADE)
    الموديل = models.CharField(max_length=20)

    def __str__(self):
        return self.الموديل

class newCar(models.Model):
    modelId = models.ForeignKey(model ,on_delete=models.CASCADE)
    الفئة =models.CharField(max_length=20)
    السنة = models.IntegerField()
    السعر = models.FloatField(max_length=10)

class image(models.Model):
    carID =models.ForeignKey(newCar ,on_delete=models.CASCADE)
    صورة = models.ImageField(default='default.jpg', upload_to='car_img')

class carDetails_Text(models.Model):
    name =models.CharField(max_length=20 , primary_key=True)

class carDetails_Bool(models.Model):
    name =models.CharField(max_length=20 , primary_key=True)


class carContents_Text(models.Model):
    class Meta:
        unique_together =(('carId', 'carDetailsId'),)

    carId =models.ForeignKey(newCar,on_delete=models.CASCADE )
    carDetailsId =models.ForeignKey(carDetails_Text,on_delete=models.CASCADE )
    value =models.CharField(max_length=50)

class carContents_Bool(models.Model):
    class Meta:
        unique_together =(('carId', 'carDetailsId'),)

    carId =models.ForeignKey(newCar,on_delete=models.CASCADE )
    carDetailsId =models.ForeignKey(carDetails_Bool,on_delete=models.CASCADE )
    value =models.BooleanField()

class publishedCar(models.Model):
    customerId =models.ForeignKey(User,on_delete=models.CASCADE )
    modelId = models.ForeignKey(model, on_delete=models.CASCADE)
    الفئة = models.CharField(max_length=20)
    السنة = models.IntegerField()
    السعر = models.FloatField(max_length=10)


class used_image(models.Model):
    carId =models.ForeignKey(publishedCar ,on_delete=models.CASCADE)
    صورة = models.ImageField(default='default.jpg', upload_to='car_img')

class publishedCarDetails_Text(models.Model):
    name =models.CharField(max_length=20 ,primary_key=True)

class publishedCarDetails_Bool(models.Model):
    name =models.CharField(max_length=20 ,primary_key=True)

class publishedCarContents_Text(models.Model):
    class Meta:
        unique_together =(('publishedCarId', 'publishedCarDetailsId'),)

    publishedCarId =models.ForeignKey(publishedCar,on_delete=models.CASCADE )
    publishedCarDetailsId =models.ForeignKey(publishedCarDetails_Text,on_delete=models.CASCADE )
    value =models.CharField(max_length=50)

class publishedCarContents_Bool(models.Model):
    class Meta:
        unique_together =(('publishedCarId', 'publishedCarDetailsId'),)

    publishedCarId =models.ForeignKey(publishedCar,on_delete=models.CASCADE )
    publishedCarDetailsId =models.ForeignKey(publishedCarDetails_Bool,on_delete=models.CASCADE )
    value =models.BooleanField()

car/views.py
from django.shortcuts import render ,redirect,get_object_or_404
from .models import *

from .form import used_car_form_txt ,used_car_form_bool ,car_form,\
    comp_form,publishedCar_form ,new_car_form_bool ,new_car_form_txt ,used_img_formset ,new_img_formset

from django.views.generic import DetailView ,DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import  staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin


#used car
class used_car(DetailView):
    model = publishedCar
    template_name = 'car/used_car.html'



#_______________________________________________________________________________________________
class delete_used_car(LoginRequiredMixin,DeleteView):
    model =publishedCar
    success_url = '/'
    template_name =  'car/delete_car.html'

    def delete(self, request, *args, **kwargs):
        object =self.get_object()

        if  object.customerId ==self.request.user or self.request.user.is_superuser:
            id =object.customerId.id
            object.delete()
            return redirect('profile' ,pk =id)

        return redirect('used_car', pk=object.id)


# _______________________________________________________________________________________________


@login_required(login_url='/login/')
def add_used_car(request):
    form_txt = used_car_form_txt(request.POST or None)
    form_bool = used_car_form_bool(request.POST or None)
    pub_form = publishedCar_form(request.POST or None)
    com_form = comp_form(request.POST or None)
    img_form = used_img_formset(request.POST or None ,request.FILES or None,queryset =image.objects.none())

    context = {'form_txt': form_txt,
               'form_bool': form_bool,
               'com_form' :com_form,
               'pub_form' :pub_form,
               'img_form' :img_form,
               'used' :1,
               }


    if request.method == 'POST':
        if form_bool.is_valid() and form_txt.is_valid() and pub_form.is_valid() and img_form.is_valid():
            car_ins = pub_form.save(commit=False)
            car_ins.customerId = request.user
            car_ins.save()

            for i, j in form_bool.cleaned_data.items() :
                d =publishedCarDetails_Bool.objects.get(name = i)
                publishedCarContents_Bool.objects.create(publishedCarId = car_ins,
                                                         publishedCarDetailsId =d,
                                                         value =j
                                                         )

            for i, j in form_txt.cleaned_data.items() :
                d =publishedCarDetails_Text.objects.get(name = i)
                publishedCarContents_Text.objects.create(publishedCarId = car_ins,
                                                         publishedCarDetailsId =d,
                                                         value =j
                                                         )

            for img in img_form:
                if img.cleaned_data:
                    img_ins =img.save(commit=False)
                    img_ins.carId =car_ins
                    img_ins.save()

            return redirect('used_car' ,pk =car_ins.id)

    return render(request , 'car/add_car.html' ,context)


#_______________________________________________________________________________________________


@login_required(login_url='/login/')
def update_used_car(request ,pk):
    car_ins =get_object_or_404(publishedCar ,id=pk)

    if request.user == car_ins.customerId:
        form_txt = used_car_form_txt(request.POST or None, instance=car_ins)
        form_bool = used_car_form_bool(request.POST or None, instance=car_ins)
        pub_form = publishedCar_form(request.POST or None, instance=car_ins)
        com_form = comp_form(request.POST or None, instance=car_ins.modelId.companyId)
        img_form = used_img_formset(request.POST or None, request.FILES or None
                                    ,queryset=used_image.objects.filter(carId =car_ins))

        context = {'form_txt': form_txt,
                   'form_bool': form_bool,
                   'com_form' :com_form,
                   'pub_form' :pub_form,
                   'img_form': img_form,
                   'pku': pk
                   }


        if request.method == 'POST':
            if form_bool.is_valid() and form_txt.is_valid() and pub_form.is_valid()and img_form.is_valid():
                car_ins = pub_form.save()

                contents_txt = publishedCarContents_Text.objects.filter(publishedCarId=car_ins)
                contents_bool = publishedCarContents_Bool.objects.filter(publishedCarId=car_ins)

                for i, j in form_bool.cleaned_data.items():
                    d = publishedCarDetails_Bool.objects.get(name=i)
                    c = contents_bool.get(publishedCarDetailsId=d)
                    c.value = j
                    c.save()

                for i, j in form_txt.cleaned_data.items():
                    d = publishedCarDetails_Text.objects.get(name=i)
                    c = contents_txt.get(publishedCarDetailsId=d)
                    c.value = j
                    c.save()

                    for img in img_form:
                        if img.cleaned_data:
                            img_ins = img.save(commit=False)
                            img_ins.carId = car_ins
                            img_ins.save()

                return redirect('used_car' ,pk =car_ins.id)

        return render(request , 'car/add_car.html' ,context)

    else:
        return redirect('used_car', pk=car_ins.id)


#_______________________________________________________________________________________________


#new car
class new_car(DetailView):
    model =newCar
    template_name = 'car/new_car.html'

#_______________________________________________________________________________________________
class delete_new_car(DeleteView):
    model = newCar
    success_url = '/'
    template_name = 'car/delete_car.html'

    def delete(self, request, *args, **kwargs):
        object =self.get_object()

        if  self.request.user.is_superuser :
            object.delete()
            return redirect('home')

        return redirect('new_car', pk=object.id)


# _______________________________________________________________________________________________

@staff_member_required
def add_new_car(request):
    form_txt = new_car_form_txt(request.POST or None)
    form_bool = new_car_form_bool(request.POST or None)
    pub_form = car_form(request.POST or None)
    com_form = comp_form(request.POST or None)
    img_form = new_img_formset(request.POST or None, request.FILES or None ,queryset =image.objects.none())


    context = {'form_txt': form_txt,
               'form_bool': form_bool,
               'com_form' :com_form,
               'pub_form' :pub_form,
               'img_form': img_form,
               }


    if request.method == 'POST':
        if form_bool.is_valid() and form_txt.is_valid() and pub_form.is_valid() and img_form.is_valid():
            car_ins = pub_form.save()

            for i, j in form_bool.cleaned_data.items() :
                d =carDetails_Bool.objects.get(name = i)
                carContents_Bool.objects.create(carId = car_ins,
                                                carDetailsId =d,
                                                value =j
                                                )

            for i, j in form_txt.cleaned_data.items() :
                d =carDetails_Text.objects.get(name = i)
                carContents_Text.objects.create(carId = car_ins,
                                                carDetailsId =d,
                                                value =j
                                                )

            for img in img_form:
                if img.cleaned_data:
                    img_ins =img.save(commit=False)
                    img_ins.carID =car_ins
                    img_ins.save()
        return redirect('new_car' ,pk =car_ins.id)

    return render(request , 'car/add_car.html' ,context)


#_______________________________________________________________________________________________


@staff_member_required
def update_new_car(request ,pk):
    car_ins = get_object_or_404(newCar, id=pk)

    pub_form = car_form(request.POST or None, instance=car_ins)
    com_form = comp_form(request.POST or None, instance=car_ins.modelId.companyId)
    form_bool = new_car_form_bool(request.POST or None, instance=car_ins)
    form_txt = new_car_form_txt(request.POST or None, instance=car_ins)
    img_form = new_img_formset(request.POST or None, request.FILES or None,queryset=image.objects.filter(carID=car_ins))

    context = {
        'pub_form': pub_form,
        'com_form': com_form,
        'form_bool': form_bool,
        'form_txt': form_txt,
        'img_form': img_form,
        'pkn': pk
    }
    if request.method == 'POST':
        if form_bool.is_valid() and form_txt.is_valid() and pub_form.is_valid()and img_form.is_valid():
            car_ins = pub_form.save()

            contents_txt = carContents_Text.objects.filter(carId=car_ins)
            contents_bool = carContents_Bool.objects.filter(carId=car_ins)

            for i, j in form_bool.cleaned_data.items() :
                d = carDetails_Bool.objects.get(name=i)
                c=contents_bool.get(carDetailsId =d)
                c.value =j
                c.save()

            for i, j in form_txt.cleaned_data.items() :
                d =carDetails_Text.objects.get(name = i)
                c = contents_txt.get(carDetailsId=d)
                c.value = j
                c.save()

            for img in img_form:
                if img.cleaned_data:
                    img_ins =img.save(commit=False)
                    img_ins.carID =car_ins
                    img_ins.save()

        return redirect('new_car', pk=car_ins.id)

car/templates/car/add_car.html
{% extends 'user/base.html' %}
{% load static %}

{% block css_file %}"{% static 'car/css/add_car.css' %}?version =51"{% endblock %}

{% block content %}

<div class="add_used_car">
    {%if pkn or pku%}
    <h1 class="main_head" >تعديل بيانات السيارة</h1>
    {%elif used%}
    <h1 class="main_head" >اضافة سيارة مستعملة</h1>
    {%else%}
    <h1 class="main_head" >اضافة سيارة جديده</h1>
    {%endif%}

    <div class="container">
        <form method="POST" enctype="multipart/form-data" id="car_form" data-models-url="{% url 'ajax_load_models' %}" novalidate> {% csrf_token %}
            {{ img_form.management_form}}

            <h2 class="sec_head">البيانات الاساسيه</h2>


            <div class="row">
                {% for field in com_form %}
                <div class="col-12 col-md-6">
                    <div class="row">
                        <span class="dark col-4 col-md-3">{{field.label_tag }} </span>
                        <span class=" data col">{{field}}</span>
                    </div>
                    {% for error in field.errors %}
                    <div class="col red ">{{ error }}</div>
                    {%endfor%}
                </div>
                {%endfor%}

                {% for field in pub_form %}
                <div class="col-12 col-md-6">
                    <div class="row">
                        <span class="dark col-4 col-md-3">{{field.label_tag }} </span>
                        <span class=" data col">{{field}}</span>
                    </div>

                    {% for error in field.errors %}
                    <div class="col red ">{{ error }}</div>
                    {%endfor%}
                </div>
                {%endfor%}

                {% for field in form_txt %}
                <div class="col-12 col-md-6">
                    <div class="row">
                        <span class="dark col-4 col-md-3">{{field.label_tag }} </span>
                        <span class=" data col">{{field}}</span>
                    </div>
                    {% for error in field.errors %}
                    <div class="col red ">{{ error }}</div>
                    {%endfor%}
                </div>

                {%endfor%}


            </div>

            <hr>
            <div class="row">
                {% for field in form_bool %}
                <div class="col-6 col-md-4">
                    <div class="row">
                        <span class=" col-1">{{field}}</span>
                        <span class="dark col">{{field.label_tag }} </span>
                    </div>
                    {% for error in field.errors %}
                    <div class="col red ">{{ error }}</div>
                    {%endfor%}
                </div>
                {%endfor%}
            </div>
            <h2 class="sec_head">صور السيارة</h2>

            <div class="row">
                {% for field in img_form %}
                <div class="col-12  ">
                    <div class="row">
                        <span class=" data col">{{field}}</span>
                    </div>
                    <hr>
                    {% for error in field.errors %}
                    <div class="col red ">{{ error }}</div>
                    {%endfor%}
                </div>
                <hr>

                {%endfor%}

            </div>

<!--
<h2 class="sec_head">بيانات اخري</h2>
            <textarea class="form-control"></textarea>-->

        </form>

    </div>

    <div class="section2">
        <div class="container">
            <div class="button">
                {%if pkn or pku%}
                <input class='send submit mb-2 btn' type="submit" form ="car_form" value="حفظ التعديلات">
                {%else%}
                <input class='send submit mb-2 btn' type="submit" form ="car_form" value="اضافة">
                {%endif%}

            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block js_file %}"{% static 'car_prediction/js/hidden.js' %}"{% endblock %}

{% block js_content %}
$("#id_الماركة").change(function () {
      var url = $("#car_form").attr("data-models-url");  // get the url of the load_models view
      var compId = $(this).val();  // get the selected company ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request 😊 localhost:8000/hr/ajax/load-cities/)
        data: {
          'الماركة': compId
          // add the country id to the GET parameters
        },
        success: function (data) {   // data is the return of the load_models view function
          $("#id_modelId").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
{% endblock %}

car/templates/car/delete_car.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}
<div class=user>
    <div class="container">
        <form method='POST'>{% csrf_token %}
            <h2 class="red main_head" >
                هل تريد حذف السيارة! <input class='del btn' type="submit" value="تأكيد الحذف">
            </h2>
        </form>
    </div>
</div>
{% endblock %}

car/templates/car/new_car.html
{% extends 'user/base.html' %}
{% load static %}
{% block css_file %}"{% static 'car/css/used_car.css' %}"{% endblock %}
{% load get_car %}


{% block content %}
<div class="used_car">
    <div class="slider">
                {%for img in object.image_set.all%}
                <div>
                    <img class ='img-fluid w-100' src="{{img.صورة.url}}" >
                </div>
                {%endfor%}
    </div>
    <div class="container">
        <div class="row justify-content-center ">
            <h2 class="col-12 col-lg-5 text-center text-lg-right">
                <span>{{ object.modelId.companyId.الماركة }}</span> -
                <span>{{ object.modelId.الموديل }}</span> -
                <span>{{ object.الفئة }}</span>
            </h2>
            <h2 class="col-12 col-lg-3 text-center text-lg-right"><span>السعر:</span>{{object.السعر}}</h2>
            <h2 class="col-12 col-lg-3 text-center text-lg-left"><span>السنة:</span>{{object.السنة}}</h2>

        </div>

        <div class="row justify-content-center mt-3">
            {% if user.is_superuser%}
            <div class="col-12 col-md-6 text-center text-md-right"><a href="{%url 'update_new_car' object.id%}" class="btn send" >تعديل المواصفات</a></div>
            <div class="col text-center text-md-left"><a href="{%url 'delete_new_car' object.id%}" class="btn send" >حذف السيارة</a></div>
            {%endif%}
        </div>
        <hr>


        <div class="car_info">
            {%for i in object|getNewText %}
                <div class="row ">
                    <div class="col">
                        <p>{{i.carDetailsId.name}}</p>
                    </div>
                    <div class="col">
                        <p>{{i.value}}</p>

                    </div>
                </div>
                <hr>
            {%endfor%}
           {%for i in object|getNewBool %}
                <div class="row">
                    <div class="col">
                        <p>{{i.carDetailsId.name}}</p>
                    </div>
                    <div class="col">
                        {% if i.value is True %}
                        <p>متوفر</p>
                        {%else%}
                        <p>غير متوفر</p>
                        {%endif%}

                    </div>
                </div>
                <hr>
            {%endfor%}
        </div>




    </div>
</div>
{% endblock %}

car/templates/car/test_model.html
<option value="">---------</option>
{% for mode in models %}
<option value="{{ mode.pk }}">{{ mode }}</option>
{% endfor %}

car/templates/car/used_car.html
{% extends 'user/base.html' %}
{% load static %}

{% block css_file %}"{% static 'car/css/used_car.css' %}"{% endblock %}
{% load get_car %}

{% block content %}
<div class="used_car">
    <div class="slider">
                {%for img in object.used_image_set.all%}
                <div>
                    <img class ='img-fluid w-100' src="{{img.صورة.url}}" >
                </div>
                {%endfor%}
    </div>
    <div class ='container'>

    <div class="row justify-content-center ">
            <h2 class="col-12 col-lg-5 text-center text-lg-right">
                <span>{{ object.modelId.companyId.الماركة }}</span> -
                <span>{{ object.modelId.الموديل }}</span> -
                <span>{{ object.الفئة }}</span>
            </h2>
            <h2 class="col-12 col-lg-3 text-center text-lg-right"><span>السعر:</span>{{object.السعر}}</h2>
            <h2 class="col-12 col-lg-3 text-center text-lg-left"><span>السنة:</span>{{object.السنة}}</h2>

    </div>


    <div class="row justify-content-center mt-3">
        {% if user == object.customerId %}
        <div class="col-12 col-md-6 text-center text-md-right"><a href="{%url 'update_used_car' object.id%}" class="btn send" >تعديل المواصفات</a></div>
        {%endif%}
        {% if user == object.customerId or user.is_superuser%}
        <div class="col text-center text-md-left"><a href="{%url 'delete_used_car' object.id%}" class="btn send" >حذف السيارة</a></div>
        {%endif%}
    </div>

    <hr>


    <div class="car_info">
        {%for i in object|getUsedText %}
            <div class="row">
                <div class="col">
                    <p>{{i.publishedCarDetailsId.name}}</p>
                </div>
                <div class="col">
                    <p>{{i.value}}</p>

                </div>
            </div>
            <hr>
        {%endfor%}


        {%for i in object|getUsedBool %}
            <div class="row">
                <div class="col">
                    <p>{{i.publishedCarDetailsId.name}}</p>
                </div>
                <div class="col">
                    {% if i.value is True %}
                    <p>متوفر</p>
                    {%else%}
                    <p>غير متوفر</p>
                    {%endif%}

                </div>
            </div>
            <hr>
        {%endfor%}
    </div>

    <!--the owner-->
    <div class="row pro_info m-5">

        <div class="col-12 col-md-6 text-center img_p_d mb-5 mb-md-0" >
            <img class =' img-fluid img-thumbnail img_p_i' src="{{object.customerId.profile.صورة_شخصية.url}}" alt="Sheldon COOPER">
            <h1 class="red">{{object.customerId.username}}</h1>
        </div>

        <div class="col mb-md-0" >
            <h2><span > الاسم:</span>{{object.customerId.profile.الاسم}}</h2>
            <h2><span>رقم الهاتف: </span>{{object.customerId.profile.رقم_الهاتف}}</h2>
            <h2><span>العنوان: </span>
                {{object.customerId.profile.المنطقة.governorateId.المحافظة}} - {{object.customerId.profile.المنطقة.المنطقة}}
            </h2>
        </div>
    </div>

     <div class="row justify-content-center">
    <a href="{%url 'profile' object.customerId.id%}" class="btn send" >عرض الصفحة الشخصية</a>
    </div>





</div>
</div>
{% endblock %}