finalProject/urls.py
from django.conf.urls import  url
from car_prediction.api import CarAdList ,CarAdDetail
from rest_framework.urlpatterns import format_suffix_patterns




from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from user.views import register, profile,profile_update ,load_regions
from django.contrib.auth import views
from home.views import home
from search.views import used_search, new_search
from car_prediction.views import prediction ,userSubmit,chrome ,home2
from car.views import add_used_car ,used_car,new_car ,load_models ,add_new_car ,update_new_car \
      ,update_used_car ,delete_new_car,delete_used_car

urlpatterns = [
      path('admin/', admin.site.urls),
      # home app____________________________________________________________________________
      path('', home, name='home'),
      # user app______________________________________________________________________
      path('register/', register.as_view(), name='register'),
      path('login/', views.LoginView.as_view(template_name='user/login.html'), name='login'),
      path('logout/', views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
      path('profile/<int:pk>/',profile, name='profile'),
      path('profile/update/',profile_update, name='profile_update'),

      # search app____________________________________________________________
      path('used_search/<str:comp>/<str:model>/', used_search.as_view(), name='used_search'),
      path('new_search/<str:comp>/<str:model>/', new_search.as_view(), name='new_search'),
      # car app_______________________________________________________
      path('used_car/<int:pk>/', used_car.as_view(), name='used_car'),
      path('new_car/<int:pk>/',new_car.as_view(), name='new_car'),

      path('add_used_car/', add_used_car, name='add_used_car'),
      path('add_new_car/', add_new_car, name='add_new_car'),

      path('update_new_car/<int:pk>/', update_new_car, name='update_new_car'),
      path('update_used_car/<int:pk>/', update_used_car, name='update_used_car'),

      path('delete_new_car/<int:pk>/', delete_new_car.as_view(), name='delete_new_car'),
      path('delete_used_car/<int:pk>/', delete_used_car.as_view(), name='delete_used_car'),
      # ajax__________________________________________________________
      path('ajax/load_models/' ,load_models ,name ='ajax_load_models' ),
      path('ajax/load_regions/' ,load_regions ,name ='ajax_load_regions' ),

      # prediction__________________________________________________________________
      path('prediction/', prediction, name='prediction'),
                    url(r'^x$', home2, name='home2'),

                    url(r'^userSubmit',userSubmit, name="userSubmit"),

                    url(r'^chrome',chrome, name="chrome"),

                    url(r'^api/ads/$',CarAdList.as_view()),
                    url(r'^api/ads/(?P<idFromSite>[0-9]+)/$', CarAdDetail.as_view())

  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = format_suffix_patterns(urlpatterns)

car/models.py
from django.db import models
from django.contrib.auth.models import User

class company(models.Model):
    الماركة = models.CharField(max_length=20)

    def __str__(self):
        return self.الماركة

class model(models.Model):
    companyId =models.ForeignKey(company ,on_delete=models.CASCADE)
    الموديل = models.CharField(max_length=20)

    def __str__(self):
        return self.الموديل

class newCar(models.Model):
    modelId = models.ForeignKey(model ,on_delete=models.CASCADE)
    الفئة =models.CharField(max_length=20)
    السنة = models.IntegerField()
    السعر = models.FloatField(max_length=10)

class image(models.Model):
    carID =models.ForeignKey(newCar ,on_delete=models.CASCADE)
    صورة = models.ImageField(default='default.jpg', upload_to='car_img')

class carDetails_Text(models.Model):
    name =models.CharField(max_length=20 , primary_key=True)

class carDetails_Bool(models.Model):
    name =models.CharField(max_length=20 , primary_key=True)


class carContents_Text(models.Model):
    class Meta:
        unique_together =(('carId', 'carDetailsId'),)

    carId =models.ForeignKey(newCar,on_delete=models.CASCADE )
    carDetailsId =models.ForeignKey(carDetails_Text,on_delete=models.CASCADE )
    value =models.CharField(max_length=50)

class carContents_Bool(models.Model):
    class Meta:
        unique_together =(('carId', 'carDetailsId'),)

    carId =models.ForeignKey(newCar,on_delete=models.CASCADE )
    carDetailsId =models.ForeignKey(carDetails_Bool,on_delete=models.CASCADE )
    value =models.BooleanField()

class publishedCar(models.Model):
    customerId =models.ForeignKey(User,on_delete=models.CASCADE )
    modelId = models.ForeignKey(model, on_delete=models.CASCADE)
    الفئة = models.CharField(max_length=20)
    السنة = models.IntegerField()
    السعر = models.FloatField(max_length=10)


class used_image(models.Model):
    carId =models.ForeignKey(publishedCar ,on_delete=models.CASCADE)
    صورة = models.ImageField(default='default.jpg', upload_to='car_img')

class publishedCarDetails_Text(models.Model):
    name =models.CharField(max_length=20 ,primary_key=True)

class publishedCarDetails_Bool(models.Model):
    name =models.CharField(max_length=20 ,primary_key=True)

class publishedCarContents_Text(models.Model):
    class Meta:
        unique_together =(('publishedCarId', 'publishedCarDetailsId'),)

    publishedCarId =models.ForeignKey(publishedCar,on_delete=models.CASCADE )
    publishedCarDetailsId =models.ForeignKey(publishedCarDetails_Text,on_delete=models.CASCADE )
    value =models.CharField(max_length=50)

class publishedCarContents_Bool(models.Model):
    class Meta:
        unique_together =(('publishedCarId', 'publishedCarDetailsId'),)

    publishedCarId =models.ForeignKey(publishedCar,on_delete=models.CASCADE )
    publishedCarDetailsId =models.ForeignKey(publishedCarDetails_Bool,on_delete=models.CASCADE )
    value =models.BooleanField()

user/models.py
from django.db import models
from django.contrib.auth.models import User

class governorate(models.Model):
    المحافظة =models.CharField(max_length=30)

    def __str__(self):
        return self.المحافظة


class region(models.Model):
    governorateId =models.ForeignKey(governorate ,on_delete=models.CASCADE)
    المنطقة =models.CharField(max_length=30)

    def __str__(self):
        return self.المنطقة



class profile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    الاسم = models.CharField( max_length=20  ,default="-")
    صورة_شخصية = models.ImageField(default='default.png' , upload_to='profile_img')
    رقم_الهاتف = models.CharField( max_length=13,default="-")
    المنطقة =models.ForeignKey(region ,on_delete=models.CASCADE ,null=True ,blank=True)

user/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .form import UserUpdateForm, ProfileUpdateForm ,governorate_form
from .models import region
from django.contrib.auth.decorators import login_required

class register(CreateView):
    template_name = 'user/register.html'
    form_class = UserCreationForm
    success_url = '/login'


def profile(request, pk):
    person = User.objects.get(id=pk)

    context = {
        'person': person,
    }

    return render(request, 'user/profile.html', context)

@login_required(login_url='/login/')
def profile_update(request):
    g_form = governorate_form(request.POST or None ,instance=request.user)
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            i =request.user.id
            return redirect('/profile/' +str(i))

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'g_form' :g_form
    }

    return render(request, 'user/profile_update.html', context)


#ajax
def load_regions(request):
    gov =request.GET.get('المحافظة')
    regions =region.objects.filter(governorateId = gov)

    return render(request ,'user/test_region.html' ,{'regions' :regions})

user/templates/user/base.html
<!DOCTYPE html>
{% load static %}
<html dir ='rtl'>
<head>
    <meta charset="UTF-8">
    <title>YourCar</title>
    <link rel="icon" type="image/png" href="{% static 'user/images/CabrioletRed.png' %}" />
    <link rel="stylesheet" href= "{% static 'user/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href= "{% static 'user/css/bootstrap_rtl.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/fontawesome-all.css' %}" />
    <link rel="stylesheet" href="{% static 'user/bxslider-4-4.2.12/src/css/jquery.bxslider.css' %}">
    <link rel="stylesheet" href= "{% static 'user/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'user/bxslider-4-4.2.12/src/css/jquery.bxslider.css' %}">
    <link rel="stylesheet" href= {% block css_file %}{% endblock %}>

</head>
<body>
<!-----------------------------------
                 To Up Button
        ----------------------- ---------->
    <div class="container-fluied">
        <div class="to-up">
            <i class="fa fa-arrow-up main-color fa-2x"></i>
        </div>
    </div>

<!-- ---------------------------------
             nav bar
    ----------------------- -------- -->
<nav class="navbar navbar-expand-xl navbar-dark p-0 fixed-top">
    <div class="container">
        <!-- Brand -->
        <a href="{%url 'home'%}" class="navbar-brand p-0">
            <img src="{% static 'user/images/CabrioletRed.png' %}" />
            <span> YourCar</span>
        </a>

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainnav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="text-center collapse navbar-collapse" id="mainnav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'add_used_car'%}" data-scroll="home">أضف سيارتك</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'home'%}#portfolio" data-scroll="about">المعرض</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" data-scroll="work">تواصل معنا</a>
                </li>



                {% if user.is_authenticated %}
                <a href="{%url 'profile' user.pk%}"class="btn btn-danger " >الصفحة الشخصية</a>
                <a href="{%url 'logout'%}"class="btn btn-danger " >تسجيل الخروج</a>
                {%else%}
                <a href="{%url 'login'%}"class="btn btn-danger ">تسجيل الدخول</a>
                <a href="{%url 'register'%}" class="btn btn-danger " >التسجيل</a>
                {%endif%}



            </ul>
        </div>
    </div>
</nav>
{% block content %} {% endblock %}

<!--footer-->

<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footerRight clo-12 col-md-6">
          <div class="con1"><i class="fa fa-phone" style="font-size: 40px;"></i>
            <span style="font-size: 20px">0125678999</span></div>
            <div class="con1"><i class="fa fa-envelope"></i>
            <span style="font-size: 20px">company name @gmail.com</span></div>
            </div>



            <div class="footerLeft clo-12 col-md-6">
                <div class="row">

                    <div class=" col-2 icoone">
                <i class="fab fa-facebook-square fa-3x" ></i>
                </div>
                <div class="col-2 icotwo">
             <i class="fab fa-linkedin  fa-3x"></i>
                </div>

                <div class="col-2 icothree">
                <i class="fab fa-twitter-square  fa-3x"></i>
                </div>

                <div class="col-2 icofour">
               <i class="fab fa-behance-square  fa-3x"></i>
                </div>
                </div>

            </div>
        </div>


        <div class="row">
            <div class="col">
            <p style="font-size: 20px"> copy right <span style="color: #d72c1a;"> &#64; </span>  YourCar</p>
            </div>
        </div>
    </div>


        </div>

    <script src="{% static 'user/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'user/js/popper.min.js' %}"></script>
    <script src="{% static 'user/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'user/js/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'user/js/user.js' %}"></script>
    <script src="{% static 'user/bxslider-4-4.2.12/src/js/jquery.bxslider.js' %}"></script>
    <script src={% block js_file %}{% endblock %}></script>
    <script>{% block js_content %}{% endblock %}</script>




</body>
</html>

user/templates/user/login.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}
<div class="user">
    <h1 class="main_head dark">تسجيل الدخول</h1>

    <div class="info_form">
        <div class="container">
            <form method='POST'>{% csrf_token %}
                {% for field in form %}

                <div class="row">
                    <div class="col-4 dark ">{{field.label_tag }}</div>
                    <div class="col-8">{{field}}</div>

                    {% for error in field.errors %}
                    <div class="col red ">{{ error }}</div>
                    {%endfor%}
                </div>

                {%endfor%}

                <div class='submit'>
                    <input class='send_button btn' type="submit" value="تسجيل">
                    <a class = "dark" href ="{%url 'register'%}">تسجيل اشتراك جديد ؟</a>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

user/templates/user/logout.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}
<div class=user>
    <div class="container">
    <h2 class="red main_head" style="font-size: 30px">Log out successfully! <a href="{%url 'login'%}" class="dark a_logout">تسجيل الدخول</a></h2>
    </div>
</div>

{% endblock %}

user/templates/user/profile.html
{% extends 'user/base.html' %}
{% load static %}
{% load filter %}


{% block css_file %}"{% static 'user/css/profile.css' %}"{% endblock %}

{% block content %}
<div class =profile>

    <div class="container">
        <div class="row pro_info p-5">

            <div class="col-12 col-md-6 text-center img_p_d">
                <img class =' img-fluid img_p_i' src="{{person.profile.صورة_شخصية.url}}" alt="Sheldon COOPER">
                <h1 class="red">{{person.username}}</h1>
            </div>

            <div class="col" >
                <h2><span > الاسم:</span>{{person.profile.الاسم}}</h2>
                <h2><span>رقم الهاتف: </span>{{person.profile.رقم_الهاتف}}</h2>
                <h2><span>العنوان: </span>
                    {{person.profile.المنطقة.governorateId.المحافظة}} - {{person.profile.المنطقة.المنطقة}}
                </h2>
            </div>
        </div>

        <div class="row">
            {%if user == person%}
            <a href="{%url 'profile_update'%}" class="btn send" >تعديل الصفحة الشخصية</a>
            {%endif%}
        </div>



        <hr>
    </div>



    <div class="container-fluid">
        <h1 class="red text-center m-5">سيارات قام {{person.profile.الاسم}} باضافتها</h1>


        {%for i in person|user_car %}
        <div class="row pro_info">
            <div class="col-12 col-md-6 text-center img_c_d">
                <img class ='img_c_i 'src="{{i.used_image_set.first.صورة.url}}" >
                <button style="margin:15px auto" class="btn send"><a href="{%url 'used_car' i.id%}">عرض التفاصيل</a></button>
            </div>

            <div class="col m-5">
                <h2>
                    <span>{{ i.modelId.companyId.الماركة }}</span> -
                    <span>{{ i.modelId.الموديل }}</span> -
                    <span>{{ i.الفئة }}</span>
                </h2>
                <h2><span>السعر:</span>{{i.السعر}}</h2>
                <h2><span>سرعة المحرك:</span>{{i|used_car_detail_txt:'سرعة المحرك'}}</h2>
                <h2><span>عدد الكيلوات:</span>{{i|used_car_detail_txt:'عدد الكيلوات'}}</h2>
            </div>
        </div>
            <hr>
            {%endfor%}



    </div>
</div>

{% endblock %}

user/templates/user/profile_update.html
{% extends 'user/base.html' %}
{% load static %}

{% block css_file %}"{% static 'user/css/profile.css' %}"{% endblock %}

{% block content %}

<div class="profile">
    <h1 class="main_head" >تعديل بياناتك</h1>

    <div class="container-fluid">
        <form method='POST' enctype="multipart/form-data" id="profile_form" data-models-url="{% url 'ajax_load_regions' %}" novalidate>{% csrf_token %}
            <div class="row">
                {% for field in u_form %}
                <div class="col-12 col-md-6">
                    <div class="row">
                        <span class="dark col-4 col-md-3">{{field.label_tag }} </span>
                        <span class=" data col">{{field}}</span>
                    </div>
                </div>
                {%endfor%}

                {% for field in g_form %}
                <div class="col-12 col-md-6">
                    <div class="row">
                        <span class="dark col-4 col-md-3">{{field.label_tag }} </span>
                        <span class=" data col">{{field}}</span>
                    </div>
                </div>
                {%endfor%}

                {% for field in p_form %}
                <div class="col-12 col-md-6">
                    <div class="row">
                        <span class="dark col-4 col-md-3">{{field.label_tag }} </span>
                        <span class=" data col">{{field}}</span>
                    </div>
                </div>
                {%endfor%}


            </div>
            <input type="submit" value="حفط البيانات" class='send btn'>

    </form>
    </div>
</div>


{% endblock %}


{% block js_content %}
$("#id_المحافظة").change(function () {
      var url = $("#profile_form").attr("data-models-url");  // get the url of the load_models view
      var govId = $(this).val();  // get the selected company ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request 😊 localhost:8000/hr/ajax/load-cities/)
        data: {
          'المحافظة': govId
          // add the gov id to the GET parameters
        },
        success: function (data) {   // data is the return of the load_models view function
          $("#id_المنطقة").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
{% endblock %}

user/templates/user/register.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}
<div class="user">
    <h1 class="main_head dark">تسجيل حساب جديد</h1>

    <div class="info_form">
        <div class="container">
            <form method='POST'>{% csrf_token %}
               {% for field in form %}

                <div class="row">
                    <div class="col-4 dark ">{{field.label_tag }}</div>
                    <div class="col-8">{{field}}</div>


                    {% for error in field.errors %}
                   <div class="col red ">{{ error }}</div>
                    {%endfor%}
                </div>

                {%endfor%}


                <div class='submit'>
                    <input class='send_button btn' type="submit" value="تسجيل">
                    <a class = "dark" href ="{%url 'login'%}">هل لديك حساب بالفعل ؟</a>
                </div>
            </form>
        </div>

    </div>
</div>


{% endblock %}

user/templates/user/test_region.html
<option value="">---------</option>
{% for r in regions %}
<option value="{{ r.pk }}">{{ r }}</option>
{% endfor %}